<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>8647c140-62eb-440c-8c6d-bee5bc05eb14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24CHfevXGjl2Ocdt1yi72vY7bXDw3DL-oeHthARezUCTB7Wr44dLqX0PM7E9OtphhSVvs9iTMU73iAkfL9qVgIvU8yRKKBCC-KBK-yPMa-tJOoLZR1bZoD6mrjUAaLpyVcz-IAH0mZugFlaSQqVoBOGqMEEuvf9dXD1wm5A_L8So2uWIkO9P_Bj3IPVq_bsZoswUJAP&amp;k=6Lfa6Q0TAAAAACcH--9Vp8VZ2159EbHJAtc8ld4q</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/micro staging/Page_Olay Holiday Program/iframe_html1body1div6div4iframe1_c-fbt95gmngblq</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24CHfevXGjl2Ocdt1yi72vY7bXDw3DL-oeHthARezUCTB7Wr44dLqX0PM7E9OtphhSVvs9iTMU73iAkfL9qVgIvU8yRKKBCC-KBK-yPMa-tJOoLZR1bZoD6mrjUAaLpyVcz-IAH0mZugFlaSQqVoBOGqMEEuvf9dXD1wm5A_L8So2uWIkO9P_Bj3IPVq_bsZoswUJAP&amp;k=6Lfa6Q0TAAAAACcH--9Vp8VZ2159EbHJAtc8ld4q')])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
